{{- if and .Values.ingressroute.enabled .Values.ingressroute.mtls.enabled }}
apiVersion: v1
data:
  ca.crt: {{ .Values.ingressroute.mtls.caCrt | b64enc }}
kind: Secret
metadata:
  name: {{ include "kad.fullname" . }}-root-ca
type: Opaque
{{- end }}
