{{- if and .Values.ingressroute.enabled .Values.ingressroute.mtls.enabled }}
apiVersion: v1
data:
  tls.crt: {{ .Values.ingressroute.mtls.tlsCrt | b64enc }}
  tls.key: {{ .Values.ingressroute.mtls.tlsKey | b64enc }}
kind: Secret
metadata:
  name: {{ include "kad.fullname" . }}-server-cert
type: kubernetes.io/tls
{{- end }}
